const movieJSON = [
    {
        "anime_id": 33185,
        "title": "Peace Maker Kurogane Movie 1: Omou Michi",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/1379/91338.jpg",
        "source": "Manga",
        "status": "Not yet aired",
        "airing": false,
        "aired": {"from": "2018-06-02", "to": "2018-06-02"},
        "duration": "Unknown",
        "rating": "R - 17+ (violence & profanity)",
        "score": 0,
        "scored_by": 0,
        "rank": null,
        "popularity": 5215,
        "related": {"Adaptation": [{"mal_id": 473, "type": "manga", "url": "https://myanimelist.net/manga/473/Peace_Maker_Kurogane", "title": "Peace Maker Kurogane"}], "Prequel": [{"mal_id": 161, "type": "anime", "url": "https://myanimelist.net/anime/161/Peace_Maker_Kurogane", "title": "Peace Maker Kurogane"}], "Sequel": [{"mal_id": 36556, "type": "anime", "url": "https://myanimelist.net/anime/36556/Peace_Maker_Kurogane_Movie_2__Yuumei", "title": "Peace Maker Kurogane Movie 2: Yuumei"}]},
        "producer": "",
        "licensor": "",
        "studio": "White Fox",
        "genre": "Action, Comedy, Historical, Samurai, Shounen",
        "opening_theme": [],
        "ending_theme": ["Rust by THE JETZEJOHNSON (ジェッジジョンソン)"]
      },
      {
        "anime_id": 35277,
        "title": "Nanumu no Ie",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/4/84973.jpg",
        "source": "Other",
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": null, "to": null},
        "duration": "1 hr. 36 min.",
        "rating": "PG - Children",
        "score": 4.86,
        "scored_by": 7,
        "rank": 11408,
        "popularity": 13987,
        "related": [],
        "producer": "",
        "licensor": "",
        "studio": "",
        "genre": "Drama, Historical",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 14353,
        "title": "Death Billiards",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/11/48721.jpg",
        "source": "Original",
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2013-03-02", "to": "2013-03-02"},
        "duration": "25 min.",
        "rating": "R - 17+ (violence & profanity)",
        "score": 8.01,
        "scored_by": 81162,
        "rank": 542,
        "popularity": 637,
        "related": {"Other": [{"mal_id": 13863, "type": "anime", "url": "https://myanimelist.net/anime/13863/Arve_Rezzle__Kikaijikake_no_Yousei-tachi", "title": "Arve Rezzle: Kikaijikake no Yousei-tachi"}, {"mal_id": 14347, "type": "anime", "url": "https://myanimelist.net/anime/14347/Ryo", "title": "Ryo"}, {"mal_id": 14349, "type": "anime", "url": "https://myanimelist.net/anime/14349/Little_Witch_Academia", "title": "Little Witch Academia"}], "Alternative version": [{"mal_id": 28223, "type": "anime", "url": "https://myanimelist.net/anime/28223/Death_Parade", "title": "Death Parade"}]},
        "producer": "",
        "licensor": "Funimation",
        "studio": "Madhouse",
        "genre": "Game, Mystery, Psychological, Drama, Thriller",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 8154,
        "title": "Gegege no Kitarou: Saikyou Youkai Gundan! Nippon Jouriku!!",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/5/27356.jpg",
        "source": "Unknown",
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "1986-07-12", "to": "1986-07-12"},
        "duration": "49 min.",
        "rating": "G - All Ages",
        "score": 6.17,
        "scored_by": 60,
        "rank": 6853,
        "popularity": 10204,
        "related": {"Parent story": [{"mal_id": 7307, "type": "anime", "url": "https://myanimelist.net/anime/7307/Gegege_no_Kitarou_1985", "title": "Gegege no Kitarou (1985)"}]},
        "producer": "",
        "licensor": "",
        "studio": "Toei Animation",
        "genre": "Adventure, Comedy, Fantasy, Horror, Supernatural",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 35594,
        "title": "Ylion to Callysia",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/8/85786.jpg",
        "source": "Original",
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2017-06-04", "to": "2017-06-04"},
        "duration": "8 min.",
        "rating": null,
        "score": 5.86,
        "scored_by": 7,
        "rank": 12762,
        "popularity": 10399,
        "related": [],
        "producer": "Dwango",
        "licensor": "",
        "studio": "",
        "genre": "Action, Fantasy",
        "opening_theme": [],
        "ending_theme": []
      }
];

module.exports = movieJSON;