const ovaJSON = [
    {
        "anime_id": 16642,
        "title": "Ane Koi: Suki Kirai Daisuki.",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/5/47029.jpg",
        "source": "Manga",
        "episodes": 2,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2013-02-15", "to": "2013-05-17"},
        "duration": "26 min. per ep.",
        "rating": "Rx - Hentai",
        "score": 7.03,
        "scored_by": 2355,
        "rank": null,
        "popularity": 4667,
        "related": {"Adaptation": [{"mal_id": 38145, "type": "manga", "url": "https://myanimelist.net/manga/38145/Ane_Koi", "title": "Ane Koi"}]},
        "producer": "Pashmina",
        "licensor": "",
        "studio": "",
        "genre": "Hentai",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 9389,
        "title": "Ginga Hyouryuu Vifam: Kieta 12-nin",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/11/59747.jpg",
        "source": "Unknown",
        "episodes": 1,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "1985-02-25", "to": "1985-02-25"},
        "duration": "57 min.",
        "rating": "G - All Ages",
        "score": 6.29,
        "scored_by": 102,
        "rank": 6435,
        "popularity": 10547,
        "related": {"Parent story": [{"mal_id": 2987, "type": "anime", "url": "https://myanimelist.net/anime/2987/Ginga_Hyouryuu_Vifam", "title": "Ginga Hyouryuu Vifam"}]},
        "producer": "",
        "licensor": "",
        "studio": "Sunrise",
        "genre": "Sci-Fi, Adventure, Space, Mecha",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 34152,
        "title": "Super Danganronpa 2.5: Komaeda Nagito to Sekai no Hakaimono",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/10/83150.jpg",
        "source": "Original",
        "episodes": 1,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2017-01-12", "to": "2017-01-12"},
        "duration": "25 min.",
        "rating": "R - 17+ (violence & profanity)",
        "score": 7.4,
        "scored_by": 15423,
        "rank": 2049,
        "popularity": 2044,
        "related": {"Sequel": [{"mal_id": 32189, "type": "anime", "url": "https://myanimelist.net/anime/32189/Danganronpa_3__The_End_of_Kibougamine_Gakuen_-_Mirai-hen", "title": "Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen"}, {"mal_id": 34103, "type": "anime", "url": "https://myanimelist.net/anime/34103/Danganronpa_3__The_End_of_Kibougamine_Gakuen_-_Kibou-hen", "title": "Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen"}], "Prequel": [{"mal_id": 33028, "type": "anime", "url": "https://myanimelist.net/anime/33028/Danganronpa_3__The_End_of_Kibougamine_Gakuen_-_Zetsubou-hen", "title": "Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen"}]},
        "producer": "",
        "licensor": "",
        "studio": "Lerche",
        "genre": "Action, Mystery, Horror, Psychological",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 9998,
        "title": "Chuuhai Lemon: Love 30s - Ame ni Nurete mo",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/6/27716.jpg",
        "source": "Unknown",
        "episodes": 1,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "1985-10-21", "to": "1985-10-21"},
        "duration": "44 min.",
        "rating": "PG-13 - Teens 13 or older",
        "score": 6,
        "scored_by": 28,
        "rank": 9895,
        "popularity": 11667,
        "related": [],
        "producer": "Tsuchida Productions, Wonder Kids",
        "licensor": "",
        "studio": "",
        "genre": "Police, Comedy, Romance, Drama",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 27417,
        "title": "Diabolik Lovers OVA",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/12/74238.jpg",
        "source": "Visual novel",
        "episodes": 1,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2015-02-26", "to": "2015-02-26"},
        "duration": "11 min.",
        "rating": "PG-13 - Teens 13 or older",
        "score": 6.04,
        "scored_by": 9290,
        "rank": 7260,
        "popularity": 2721,
        "related": {"Parent story": [{"mal_id": 17513, "type": "anime", "url": "https://myanimelist.net/anime/17513/Diabolik_Lovers", "title": "Diabolik Lovers"}]},
        "producer": "Frontier Works",
        "licensor": "",
        "studio": "Production I.G, Zexcs",
        "genre": "Harem, School, Vampire, Shoujo",
        "opening_theme": [],
        "ending_theme": ["DIABOLIK LOVERS DARK FATE by Yuki Sugiura"]
      }
];

module.exports = ovaJSON;