const showJSON = [
    {
    "anime_id": 40010,
    "title": "Inu x Boku SS",
    "image_url": "https://myanimelist.cdn-dena.com/images/anime/12/35893.jpg",
    "source": "Manga",
    "episodes": 12,
    "status": "Finished Airing",
    "airing": false,
    "aired": {"from": "2012-01-13", "to": "2012-03-30"},
    "duration": "24 min. per ep.",
    "rating": "PG-13 - Teens 13 or older",
    "score": 7.63,
    "scored_by": 139250,
    "rank": 1274,
    "popularity": 231,
    "premiered": "Winter 2012",
    "broadcast": "Fridays at Unknown",
    "related": {"Adaptation": [{"mal_id": 17207, "type": "manga", "url": "https://myanimelist.net/manga/17207/Inu_x_Boku_SS", "title": "Inu x Boku SS"}], "Sequel": [{"mal_id": 13403, "type": "anime", "url": "https://myanimelist.net/anime/13403/Inu_x_Boku_SS_Special", "title": "Inu x Boku SS Special"}]},
    "producer": "Aniplex, Square Enix, Mainichi Broadcasting System, Movic, Inu x Boku SS Production Partners",
    "licensor": "Sentai Filmworks",
    "studio": "David Production",
    "genre": "Comedy, Supernatural, Romance, Shounen",
    "opening_theme": ["Nirvana by MUCC"],
    "ending_theme": ["#1: Nirvana by MUCC (eps 1, 11-12)", "#2: Rakuen no Photograph (楽園のPhotograph) by Soushi Miketsukami (Yuichi Nakamura) (eps 2, 9)", "#3: Kimi wa (君は) by Ririchiyo Shirakiin (Rina Hidaka) (eps 3, 8)", "#4: one way by Banri Watanuki (Takuya Eguchi) & Zange Natsume (Mamoru Miyano) (ep 4)", "#5: SM Hantei Forum (SM判定フォーラム) by Kagerou Shoukiin (Tomokazu Sugita) (ep 5, 10)", "#6: sweets parade by Karuta Roromiya (Kana Hanazawa) (ep 6)", "#7: Taiyou to Tsuki (太陽と月) by Renshou Sorinozuka (Yoshimasa Hosoya) & Nobara Yukinokouji (Youko Hikasa) (ep 7)"]
  },
  {
    "anime_id": 40011,
    "title": "Seto no Hanayome",
    "image_url": "https://myanimelist.cdn-dena.com/images/anime/13/58383.jpg",
    "source": "Manga",
    "episodes": 26,
    "status": "Finished Airing",
    "airing": false,
    "aired": {"from": "2007-04-02", "to": "2007-10-01"},
    "duration": "24 min. per ep.",
    "rating": "PG-13 - Teens 13 or older",
    "score": 7.89,
    "scored_by": 91206,
    "rank": 727,
    "popularity": 366,
    "premiered": "Spring 2007",
    "broadcast": "Unknown",
    "related": {"Adaptation": [{"mal_id": 759, "type": "manga", "url": "https://myanimelist.net/manga/759/Seto_no_Hanayome", "title": "Seto no Hanayome"}], "Sequel": [{"mal_id": 4163, "type": "anime", "url": "https://myanimelist.net/anime/4163/Seto_no_Hanayome_OVA", "title": "Seto no Hanayome OVA"}], "Side story": [{"mal_id": 5199, "type": "anime", "url": "https://myanimelist.net/anime/5199/Seto_no_Hanayome_Fan_Disc", "title": "Seto no Hanayome Fan Disc"}], "Alternative version": [{"mal_id": 28385, "type": "anime", "url": "https://myanimelist.net/anime/28385/Seto_no_Hanayome_Picture_Drama", "title": "Seto no Hanayome Picture Drama"}]},
    "producer": "TV Tokyo, AIC, Square Enix, Sotsu",
    "licensor": "Funimation",
    "studio": "Gonzo",
    "genre": "Comedy, Parody, Romance, School, Shounen",
    "opening_theme": ["Romantic summer by SUN&LUNAR"],
    "ending_theme": ["#1: Ashita e no Hikari (明日への光) by Asuka Hinoi (1-13, 26)", "#2: Dan Dan Dan by SUN&LUNAR (eps 14-25)"]
  },
  {
    "anime_id": 40012,
    "title": "Shugo Chara!! Doki",
    "image_url": "https://myanimelist.cdn-dena.com/images/anime/11/10645.jpg",
    "source": "Manga",
    "episodes": 51,
    "status": "Finished Airing",
    "airing": false,
    "aired": {"from": "2008-10-04", "to": "2009-09-25"},
    "duration": "24 min. per ep.",
    "rating": "PG - Children",
    "score": 7.55,
    "scored_by": 37129,
    "rank": 1508,
    "popularity": 1173,
    "premiered": "Fall 2008",
    "broadcast": "Unknown",
    "related": {"Adaptation": [{"mal_id": 101, "type": "manga", "url": "https://myanimelist.net/manga/101/Shugo_Chara", "title": "Shugo Chara!"}], "Prequel": [{"mal_id": 2923, "type": "anime", "url": "https://myanimelist.net/anime/2923/Shugo_Chara", "title": "Shugo Chara!"}], "Sequel": [{"mal_id": 7082, "type": "anime", "url": "https://myanimelist.net/anime/7082/Shugo_Chara_Party", "title": "Shugo Chara! Party!"}]},
    "producer": "TV Tokyo, Sotsu",
    "licensor": "",
    "studio": "Satelight",
    "genre": "Comedy, Magic, School, Shoujo",
    "opening_theme": ["#1: Minna no Tamago (みんなのたまご) by Shugo Chara Egg (eps 1-13)", "#2: Shugo Shugo! (しゅごしゅご!) by Shugo Chara Egg (eps 14-25)", "#3: Omakase♪Guardian (おまかせ♪ガーディアン) by Guardians 4 (eps 26-38)", "#4: School Days by Guardians 4 (eps 39-51)"],
    "ending_theme": ["#1: Rottara Rottara (ロッタラ ロッタラ) by Buono! (eps 1-17)", "#2: co.no.mi.chi Buono! (eps 18-25)", "#3: MY BOY by Buono! (eps 26-38)", "#4: Take it Easy! by Buono! (eps. 39-50)", "#5: Honto no Jibun (ホントのじぶん) by Buono! (ep 51)"]
  },
  {
    "anime_id": 40013,
    "title": "Princess Tutu",
    "image_url": "https://myanimelist.cdn-dena.com/images/anime/13/32209.jpg",
    "source": "Original",
    "episodes": 38,
    "status": "Finished Airing",
    "airing": false,
    "aired": {"from": "2002-08-16", "to": "2003-05-23"},
    "duration": "16 min. per ep.",
    "rating": "PG-13 - Teens 13 or older",
    "score": 8.21,
    "scored_by": 36501,
    "rank": 307,
    "popularity": 916,
    "premiered": "Summer 2002",
    "broadcast": "Fridays at Unknown",
    "related": {"Adaptation": [{"mal_id": 1581, "type": "manga", "url": "https://myanimelist.net/manga/1581/Princess_Tutu", "title": "Princess Tutu"}], "Summary": [{"mal_id": 3265, "type": "anime", "url": "https://myanimelist.net/anime/3265/Princess_Tutu_Recaps", "title": "Princess Tutu Recaps"}]},
    "producer": "Memory-Tech, GANSIS, Marvelous AQL",
    "licensor": "ADV Films",
    "studio": "Hal Film Maker",
    "genre": "Comedy, Drama, Magic, Romance, Fantasy",
    "opening_theme": ["Morning Grace by Ritsuko Okazaki"],
    "ending_theme": ["Watashi No Ai Wa Chiisaikeredo by Ritsuko Okazaki"]
  },
  {
    "anime_id": 40014,
    "title": "Bakuman. 3rd Season",
    "image_url": "https://myanimelist.cdn-dena.com/images/anime/6/41845.jpg",
    "source": "Manga",
    "episodes": 25,
    "status": "Finished Airing",
    "airing": false,
    "aired": {"from": "2012-10-06", "to": "2013-03-30"},
    "duration": "24 min. per ep.",
    "rating": "PG-13 - Teens 13 or older",
    "score": 8.67,
    "scored_by": 107767,
    "rank": 50,
    "popularity": 426,
    "premiered": "Fall 2012",
    "broadcast": "Unknown",
    "related": {"Adaptation": [{"mal_id": 9711, "type": "manga", "url": "https://myanimelist.net/manga/9711/Bakuman", "title": "Bakuman."}], "Prequel": [{"mal_id": 10030, "type": "anime", "url": "https://myanimelist.net/anime/10030/Bakuman_2nd_Season", "title": "Bakuman. 2nd Season"}, {"mal_id": 15711, "type": "anime", "url": "https://myanimelist.net/anime/15711/Bakuman__Deraman", "title": "Bakuman.: Deraman."}], "Other": [{"mal_id": 23361, "type": "anime", "url": "https://myanimelist.net/anime/23361/Bakuman_3rd_Season_Specials", "title": "Bakuman. 3rd Season Specials"}]},
    "producer": "NHK, Shueisha",
    "licensor": "",
    "studio": "J.C.Staff",
    "genre": "Comedy, Drama, Romance, Shounen",
    "opening_theme": ["#1: Moshimo no Hanashi (もしもの話) by nano.RIPE (eps 1-13)", "#2: 23:40 (23時40分) feat. Base Ball Bear by Hyadain (eps 14-25)"],
    "ending_theme": ["#1: Pride on Everyday by Sphere (eps 1-13)", "#2: Yume Sketch (夢スケッチ) by JAM Project (eps 14-24)", "#3: Moshimo no Hanashi (もしもの話) by nano.RIPE (ep 25)"]
  }];

  module.exports = showJSON;