const specialJSON = [
    {
        "anime_id": 40015,
        "title": "Lupin III: Lupin Ikka Seizoroi",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/2/46379.jpg",
        "source": "Unknown",
        "episodes": 1,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2012-03-28", "to": "2012-03-28"},
        "duration": "10 min.",
        "rating": "PG-13 - Teens 13 or older",
        "score": 6.87,
        "scored_by": 676,
        "rank": 4041,
        "popularity": 6950,
        "related": {"Other": [{"mal_id": 1412, "type": "anime", "url": "https://myanimelist.net/anime/1412/Lupin_III", "title": "Lupin III"}]},
        "producer": "Tokyo Movie Shinsha",
        "licensor": "",
        "studio": "",
        "genre": "Adventure, Comedy, Seinen",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 40016,
        "title": "Ben-To Picture Drama",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/13/34953.jpg",
        "source": "Light novel",
        "episodes": 6,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2011-12-21", "to": "2012-05-16"},
        "duration": "9 min. per ep.",
        "rating": "PG-13 - Teens 13 or older",
        "score": 6.15,
        "scored_by": 2806,
        "rank": 6924,
        "popularity": 3977,
        "related": {"Other": [{"mal_id": 10396, "type": "anime", "url": "https://myanimelist.net/anime/10396/Ben-To", "title": "Ben-To"}]},
        "producer": "AT-X",
        "licensor": "",
        "studio": "David Production",
        "genre": "Comedy",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 40017,
        "title": "Seikai no Monshou Special",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/9/2753.jpg",
        "source": "Light novel",
        "episodes": 1,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2000-04-07", "to": "2000-04-07"},
        "duration": "1 hr. 30 min.",
        "rating": "PG-13 - Teens 13 or older",
        "score": 7.35,
        "scored_by": 1050,
        "rank": 2254,
        "popularity": 6165,
        "related": {"Full story": [{"mal_id": 290, "type": "anime", "url": "https://myanimelist.net/anime/290/Seikai_no_Monshou", "title": "Seikai no Monshou"}]},
        "producer": "Bandai Visual, WOWOW, BeSTACK",
        "licensor": "",
        "studio": "Sunrise",
        "genre": "Action, Military, Romance, Sci-Fi, Space",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 40018,
        "title": "Tegamibachi Gakuen",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/4/19573.jpg",
        "source": "Original",
        "episodes": 25,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2010-01-27", "to": "2010-07-23"},
        "duration": "3 min. per ep.",
        "rating": "PG-13 - Teens 13 or older",
        "score": 7.42,
        "scored_by": 1911,
        "rank": 1953,
        "popularity": 4119,
        "related": {"Parent story": [{"mal_id": 6444, "type": "anime", "url": "https://myanimelist.net/anime/6444/Tegamibachi", "title": "Tegamibachi"}]},
        "producer": "",
        "licensor": "",
        "studio": "Studio Pierrot",
        "genre": "Comedy",
        "opening_theme": [],
        "ending_theme": []
      },
      {
        "anime_id": 40019,
        "title": "Mobile Suit Gundam: Zeonic Front - Indignation of Zeon.",
        "image_url": "https://myanimelist.cdn-dena.com/images/anime/2/54731.jpg",
        "source": "Unknown",
        "episodes": 1,
        "status": "Finished Airing",
        "airing": false,
        "aired": {"from": "2001-09-06", "to": "2001-09-06"},
        "duration": "10 min.",
        "rating": "PG-13 - Teens 13 or older",
        "score": 5.86,
        "scored_by": 315,
        "rank": 7674,
        "popularity": 8025,
        "related": {"Full story": [{"mal_id": 80, "type": "anime", "url": "https://myanimelist.net/anime/80/Mobile_Suit_Gundam", "title": "Mobile Suit Gundam"}]},
        "producer": "Bandai",
        "licensor": "",
        "studio": "Sunrise",
        "genre": "Mecha, Military",
        "opening_theme": [],
        "ending_theme": []
      }
];

module.exports = specialJSON;